feat: add water droplet icon beside the Thirst Bar
Terasology/Thirst pull request #29
Opened 2021-10-13 12:57 UTC by mohamedation

add water droplet icon indicator on the left of the thirst bar
![Screenshot from 2021-10-13 14-53-19](https://user-images.githubusercontent.com/11461094/137137079-a6c95456-e5f1-49ab-a53b-4dcbc1a1049a.png)

2021-10-15 16:54 UTC, jdrueckert requested changes
I feel like it helps associating the contents of this file with what you can see in-game if the elements are in the same "order", aka if the icon comes first and then the bar.

Further, I think we should make the horizontal placement of the bar relative to the icon. Thus, they'll always have the same offset even if you decide to move it further right or left by adjusting the icon's horizontal placement. I would recommend the following for the bar:
```
"position-left": {
    "target": "LEFT",
    "widget": "thirstIcon",
    "offset": 45
},
```

2021-10-15 16:54 UTC, jdrueckert commented on assets/ui/Thirst.ui
> +                        "offset": 80
nitpick: should be a tad higher
```suggestion
                        "offset": 81
```

2021-10-15 16:54 UTC, jdrueckert commented on assets/ui/Thirst.ui
> +                        "offset": 12
nitpick: should be a tad more to the right
```suggestion
                        "offset": 13
```

2021-10-17 10:51 UTC, mohamedation commented
thank you. all have been revised as suggested.

2021-10-18 19:47 UTC, jdrueckert reviewed
Basically same story as for the hunger PR :wink:

2021-10-19 10:32 UTC, mohamedation commented
https://github.com/Terasology/Hunger/pull/30#issuecomment-946591630

2021-10-21 18:49 UTC, jdrueckert approved these changes

2021-10-21 18:49 UTC, merged

2021-10-21 18:55 UTC, jdrueckert commented
![](https://github.trello.services/images/mini-trello-icon.png) [Survival UI/UX improvements](https://trello.com/c/mDLqsnbp/186-survival-ui-ux-improvements)